# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170604_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
