# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170604_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
