# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170604_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default=3, max_length=20),
        ),
    ]
