# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170604_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default=3),
        ),
    ]
