# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170604_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['priority', 'due_date'], 'verbose_name_plural': 'Lists'},
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
